import type { Metadata } from "next";
import localFont from "next/font/local";
import { ClientProviders } from "@/lib/providers/ClientProviders";
import "./globals.css";
import { Header } from "@/components/Header";
import { AppSidebar } from "@/components/app-sidebar";
import { SidebarProvider } from "@/components/ui/sidebar";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="pt-BR">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<ClientProviders>
					<SidebarProvider>
						<AppSidebar />
						<main className="flex-1">
							<Header.ContainerLayout />
							{children}
						</main>
					</SidebarProvider>
				</ClientProviders>
			</body>
		</html>
	);
}
